In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Fraud_check.csv to Fraud_check.csv

In [ ]:
data=pd.read_csv("Fraud_check.csv")

In [ ]:
data.head(2)

,Undergrad,Marital.Status,Taxable.Income,City.Population,Work.Experience,Urban
0,NO,Single,68833,50047,10,YES
1,YES,Divorced,33700,134075,18,YES

In [ ]:
data.columns=['Undergrad',	'Marital_Status',	'Taxable_Income',	'City_Population',	'Work_Experience', 'Urban']

In [ ]:
data.head(2)

,Undergrad,Marital_Status,Taxable_Income,City_Population,Work_Experience,Urban
0,NO,Single,68833,50047,10,YES
1,YES,Divorced,33700,134075,18,YES

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
data[['Urban', 'Marital_Status', 'Undergrad']]=data[['Urban', 'Marital_Status', 'Undergrad']].apply(LabelEncoder().fit_transform)

In [ ]:

data.head()

,Undergrad,Marital_Status,Taxable_Income,City_Population,Work_Experience,Urban
0,0,2,68833,50047,10,1
1,1,0,33700,134075,18,1
2,0,1,36925,160205,30,1
3,1,2,50190,193264,15,1
4,0,1,81002,27533,28,0

In [ ]:
data.Taxable_Income.agg(['min','max'])

min    10003
max    99619
Name: Taxable_Income, dtype: int64

In [ ]:
data['Tax']=pd.cut(x=data.Taxable_Income, bins=[0,30000,100000], labels=['Risky', 'Good'])

In [ ]:
data.head(1)

,Undergrad,Marital_Status,Taxable_Income,City_Population,Work_Experience,Urban,Tax
0,0,2,68833,50047,10,1,Good

In [ ]:
data.Tax.value_counts()

Good     476
Risky    124
Name: Tax, dtype: int64

In [ ]:
data.tail()

,Undergrad,Marital_Status,Taxable_Income,City_Population,Work_Experience,Urban,Tax
595,1,0,76340,39492,7,1,Good
596,1,0,69967,55369,2,1,Good
597,0,0,47334,154058,0,1,Good
598,1,1,98592,180083,17,0,Good
599,0,0,96519,158137,16,0,Good

In [ ]:
data.Tax.value_counts()

Good     476
Risky    124
Name: Tax, dtype: int64

In [ ]:
data = pd.get_dummies(data,columns = ["Tax"], drop_first=True)

In [ ]:
data.head()

,Undergrad,Marital_Status,Taxable_Income,City_Population,Work_Experience,Urban,Tax_Good
0,0,2,68833,50047,10,1,1
1,1,0,33700,134075,18,1,1
2,0,1,36925,160205,30,1,1
3,1,2,50190,193264,15,1,1
4,0,1,81002,27533,28,0,1

In [ ]:
data.Tax_Good.value_counts()

#Good=1
#Risky=0

1    476
0    124
Name: Tax_Good, dtype: int64

In [ ]:

data.drop(columns='Taxable_Income', axis=1, inplace=True)

In [ ]:
data.head()

,Undergrad,Marital_Status,City_Population,Work_Experience,Urban,Tax_Good
0,0,2,50047,10,1,1
1,1,0,134075,18,1,1
2,0,1,160205,30,1,1
3,1,2,193264,15,1,1
4,0,1,27533,28,0,1

In [ ]:
#let us normalizing our data, if we use MinMax scaler all the values will be in between 0 to 1
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaled_data=scaler.fit_transform(data)

In [ ]:
scaled_data=pd.DataFrame(scaled_data)

scaled_data.columns=['Undergrad'	,'Marital_Status' ,'City_Population',	'Work_Experience'	,'Urban', 'Tax']
scaled_data.head()

   Undergrad  Marital_Status  City_Population  Work_Experience  Urban  Tax
0        0.0             1.0         0.139472         0.333333    1.0  1.0
1        1.0             0.0         0.622394         0.600000    1.0  1.0
2        0.0             0.5         0.772568         1.000000    1.0  1.0
3        1.0             1.0         0.962563         0.500000    1.0  1.0
4        0.0             0.5         0.010081         0.933333    0.0  1.0

In [ ]:

X=scaled_data.iloc[:,0:5]
Y=scaled_data['Tax']

In [ ]:
Y.value_counts()

1.0    476
0.0    124
Name: Tax, dtype: int64

In [ ]:
#let us split our data into train and lest
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((480, 5), (120, 5), (480,), (120,))

RANDOMFOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold, cross_val_score

In [ ]:
#let us use gridsearchCv and confirm the values
modd=RandomForestClassifier()
param_grid=[{'n_estimators':[80,90,100,200], 'max_features':[2,3,4,5,6]}]
gsv1=GridSearchCV(modd, param_grid, cv=10, verbose=100)

In [ ]:
gsv1.fit(X_train, Y_train)

Fitting 10 folds for each of 20 candidates, totalling 200 fits
[CV 1/10; 1/20] START max_features=2, n_estimators=80...........................
[CV 1/10; 1/20] END max_features=2, n_estimators=80;, score=0.708 total time=   0.6s
[CV 2/10; 1/20] START max_features=2, n_estimators=80...........................
[CV 2/10; 1/20] END max_features=2, n_estimators=80;, score=0.771 total time=   0.6s
[CV 3/10; 1/20] START max_features=2, n_estimators=80...........................
[CV 3/10; 1/20] END max_features=2, n_estimators=80;, score=0.771 total time=   0.7s
[CV 4/10; 1/20] START max_features=2, n_estimators=80...........................
[CV 4/10; 1/20] END max_features=2, n_estimators=80;, score=0.729 total time=   0.7s
[CV 5/10; 1/20] START max_features=2, n_estimators=80...........................
[CV 5/10; 1/20] END max_features=2, n_estimators=80;, score=0.729 total time=   0.6s
[CV 6/10; 1/20] START max_features=2, n_estimators=80...........................
[CV 6/10; 1/20] END max_features=2, n_estimators=80;, score=0.708 total time=   0.3s
[CV 7/10; 1/20] START max_features=2, n_estimators=80...........................
[CV 7/10; 1/20] END max_features=2, n_estimators=80;, score=0.792 total time=   0.2s
[CV 8/10; 1/20] START max_features=2, n_estimators=80...........................
[CV 8/10; 1/20] END max_features=2, n_estimators=80;, score=0.708 total time=   0.2s
[CV 9/10; 1/20] START max_features=2, n_estimators=80...........................
[CV 9/10; 1/20] END max_features=2, n_estimators=80;, score=0.750 total time=   0.3s
[CV 10/10; 1/20] START max_features=2, n_estimators=80..........................
[CV 10/10; 1/20] END max_features=2, n_estimators=80;, score=0.771 total time=   0.3s
[CV 1/10; 2/20] START max_features=2, n_estimators=90...........................
[CV 1/10; 2/20] END max_features=2, n_estimators=90;, score=0.771 total time=   0.3s
[CV 2/10; 2/20] START max_features=2, n_estimators=90...........................
[CV 2/10; 2/20] END max_features=2, n_estimators=90;, score=0.729 total time=   0.3s
[CV 3/10; 2/20] START max_features=2, n_estimators=90...........................
[CV 3/10; 2/20] END max_features=2, n_estimators=90;, score=0.771 total time=   0.3s
[CV 4/10; 2/20] START max_features=2, n_estimators=90...........................
[CV 4/10; 2/20] END max_features=2, n_estimators=90;, score=0.750 total time=   0.3s
[CV 5/10; 2/20] START max_features=2, n_estimators=90...........................
[CV 5/10; 2/20] END max_features=2, n_estimators=90;, score=0.750 total time=   0.2s
[CV 6/10; 2/20] START max_features=2, n_estimators=90...........................
[CV 6/10; 2/20] END max_features=2, n_estimators=90;, score=0.708 total time=   0.2s
[CV 7/10; 2/20] START max_features=2, n_estimators=90...........................
[CV 7/10; 2/20] END max_features=2, n_estimators=90;, score=0.792 total time=   0.2s
[CV 8/10; 2/20] START max_features=2, n_estimators=90...........................
[CV 8/10; 2/20] END max_features=2, n_estimators=90;, score=0.708 total time=   0.2s
[CV 9/10; 2/20] START max_features=2, n_estimators=90...........................
[CV 9/10; 2/20] END max_features=2, n_estimators=90;, score=0.771 total time=   0.2s
[CV 10/10; 2/20] START max_features=2, n_estimators=90..........................
[CV 10/10; 2/20] END max_features=2, n_estimators=90;, score=0.771 total time=   0.2s
[CV 1/10; 3/20] START max_features=2, n_estimators=100..........................
[CV 1/10; 3/20] END max_features=2, n_estimators=100;, score=0.750 total time=   0.2s
[CV 2/10; 3/20] START max_features=2, n_estimators=100..........................
[CV 2/10; 3/20] END max_features=2, n_estimators=100;, score=0.729 total time=   0.2s
[CV 3/10; 3/20] START max_features=2, n_estimators=100..........................
[CV 3/10; 3/20] END max_features=2, n_estimators=100;, score=0.750 total time=   0.2s
[CV 4/10; 3/20] START max_features=2, n_estimators=100..........................
[CV 4/10; 3/20] END max_features=2, n_estimators=100;, score=0.750 total time=   0.2s
[CV 5/10; 3/20] START max_features=2, n_estimators=100..........................
[CV 5/10; 3/20] END max_features=2, n_estimators=100;, score=0.729 total time=   0.2s
[CV 6/10; 3/20] START max_features=2, n_estimators=100..........................
[CV 6/10; 3/20] END max_features=2, n_estimators=100;, score=0.729 total time=   0.2s
[CV 7/10; 3/20] START max_features=2, n_estimators=100..........................
[CV 7/10; 3/20] END max_features=2, n_estimators=100;, score=0.792 total time=   0.2s
[CV 8/10; 3/20] START max_features=2, n_estimators=100..........................
[CV 8/10; 3/20] END max_features=2, n_estimators=100;, score=0.708 total time=   0.2s
[CV 9/10; 3/20] START max_features=2, n_estimators=100..........................
[CV 9/10; 3/20] END max_features=2, n_estimators=100;, score=0.750 total time=   0.2s
[CV 10/10; 3/20] START max_features=2, n_estimators=100.........................
[CV 10/10; 3/20] END max_features=2, n_estimators=100;, score=0.771 total time=   0.2s
[CV 1/10; 4/20] START max_features=2, n_estimators=200..........................
[CV 1/10; 4/20] END max_features=2, n_estimators=200;, score=0.771 total time=   0.4s
[CV 2/10; 4/20] START max_features=2, n_estimators=200..........................
[CV 2/10; 4/20] END max_features=2, n_estimators=200;, score=0.792 total time=   0.4s
[CV 3/10; 4/20] START max_features=2, n_estimators=200..........................
[CV 3/10; 4/20] END max_features=2, n_estimators=200;, score=0.771 total time=   0.4s
[CV 4/10; 4/20] START max_features=2, n_estimators=200..........................
[CV 4/10; 4/20] END max_features=2, n_estimators=200;, score=0.750 total time=   0.4s
[CV 5/10; 4/20] START max_features=2, n_estimators=200..........................
[CV 5/10; 4/20] END max_features=2, n_estimators=200;, score=0.729 total time=   0.4s
[CV 6/10; 4/20] START max_features=2, n_estimators=200..........................
[CV 6/10; 4/20] END max_features=2, n_estimators=200;, score=0.750 total time=   0.4s
[CV 7/10; 4/20] START max_features=2, n_estimators=200..........................
[CV 7/10; 4/20] END max_features=2, n_estimators=200;, score=0.792 total time=   0.4s
[CV 8/10; 4/20] START max_features=2, n_estimators=200..........................
[CV 8/10; 4/20] END max_features=2, n_estimators=200;, score=0.708 total time=   0.4s
[CV 9/10; 4/20] START max_features=2, n_estimators=200..........................
[CV 9/10; 4/20] END max_features=2, n_estimators=200;, score=0.750 total time=   0.4s
[CV 10/10; 4/20] START max_features=2, n_estimators=200.........................
[CV 10/10; 4/20] END max_features=2, n_estimators=200;, score=0.771 total time=   0.4s
[CV 1/10; 5/20] START max_features=3, n_estimators=80...........................
[CV 1/10; 5/20] END max_features=3, n_estimators=80;, score=0.812 total time=   0.2s
[CV 2/10; 5/20] START max_features=3, n_estimators=80...........................
[CV 2/10; 5/20] END max_features=3, n_estimators=80;, score=0.750 total time=   0.2s
[CV 3/10; 5/20] START max_features=3, n_estimators=80...........................
[CV 3/10; 5/20] END max_features=3, n_estimators=80;, score=0.812 total time=   0.2s
[CV 4/10; 5/20] START max_features=3, n_estimators=80...........................
[CV 4/10; 5/20] END max_features=3, n_estimators=80;, score=0.750 total time=   0.2s
[CV 5/10; 5/20] START max_features=3, n_estimators=80...........................
[CV 5/10; 5/20] END max_features=3, n_estimators=80;, score=0.750 total time=   0.2s
[CV 6/10; 5/20] START max_features=3, n_estimators=80...........................
[CV 6/10; 5/20] END max_features=3, n_estimators=80;, score=0.729 total time=   0.3s
[CV 7/10; 5/20] START max_features=3, n_estimators=80...........................
[CV 7/10; 5/20] END max_features=3, n_estimators=80;, score=0.812 total time=   0.3s
[CV 8/10; 5/20] START max_features=3, n_estimators=80...........................
[CV 8/10; 5/20] END max_features=3, n_estimators=80;, score=0.708 total time=   0.2s
[CV 9/10; 5/20] START max_features=3, n_estimators=80...........................
[CV 9/10; 5/20] END max_features=3, n_estimators=80;, score=0.750 total time=   0.3s
[CV 10/10; 5/20] START max_features=3, n_estimators=80..........................
[CV 10/10; 5/20] END max_features=3, n_estimators=80;, score=0.771 total time=   0.3s
[CV 1/10; 6/20] START max_features=3, n_estimators=90...........................
[CV 1/10; 6/20] END max_features=3, n_estimators=90;, score=0.771 total time=   0.3s
[CV 2/10; 6/20] START max_features=3, n_estimators=90...........................
[CV 2/10; 6/20] END max_features=3, n_estimators=90;, score=0.750 total time=   0.3s
[CV 3/10; 6/20] START max_features=3, n_estimators=90...........................
[CV 3/10; 6/20] END max_features=3, n_estimators=90;, score=0.771 total time=   0.3s
[CV 4/10; 6/20] START max_features=3, n_estimators=90...........................
[CV 4/10; 6/20] END max_features=3, n_estimators=90;, score=0.750 total time=   0.3s
[CV 5/10; 6/20] START max_features=3, n_estimators=90...........................
[CV 5/10; 6/20] END max_features=3, n_estimators=90;, score=0.667 total time=   0.3s
[CV 6/10; 6/20] START max_features=3, n_estimators=90...........................
[CV 6/10; 6/20] END max_features=3, n_estimators=90;, score=0.750 total time=   0.2s
[CV 7/10; 6/20] START max_features=3, n_estimators=90...........................
[CV 7/10; 6/20] END max_features=3, n_estimators=90;, score=0.771 total time=   0.2s
[CV 8/10; 6/20] START max_features=3, n_estimators=90...........................
[CV 8/10; 6/20] END max_features=3, n_estimators=90;, score=0.708 total time=   0.2s
[CV 9/10; 6/20] START max_features=3, n_estimators=90...........................
[CV 9/10; 6/20] END max_features=3, n_estimators=90;, score=0.729 total time=   0.2s
[CV 10/10; 6/20] START max_features=3, n_estimators=90..........................
[CV 10/10; 6/20] END max_features=3, n_estimators=90;, score=0.771 total time=   0.2s
[CV 1/10; 7/20] START max_features=3, n_estimators=100..........................
[CV 1/10; 7/20] END max_features=3, n_estimators=100;, score=0.771 total time=   0.2s
[CV 2/10; 7/20] START max_features=3, n_estimators=100..........................
[CV 2/10; 7/20] END max_features=3, n_estimators=100;, score=0.688 total time=   0.2s
[CV 3/10; 7/20] START max_features=3, n_estimators=100..........................
[CV 3/10; 7/20] END max_features=3, n_estimators=100;, score=0.792 total time=   0.2s
[CV 4/10; 7/20] START max_features=3, n_estimators=100..........................
[CV 4/10; 7/20] END max_features=3, n_estimators=100;, score=0.729 total time=   0.2s
[CV 5/10; 7/20] START max_features=3, n_estimators=100..........................
[CV 5/10; 7/20] END max_features=3, n_estimators=100;, score=0.729 total time=   0.2s
[CV 6/10; 7/20] START max_features=3, n_estimators=100..........................
[CV 6/10; 7/20] END max_features=3, n_estimators=100;, score=0.750 total time=   0.2s
[CV 7/10; 7/20] START max_features=3, n_estimators=100..........................
[CV 7/10; 7/20] END max_features=3, n_estimators=100;, score=0.812 total time=   0.2s
[CV 8/10; 7/20] START max_features=3, n_estimators=100..........................
[CV 8/10; 7/20] END max_features=3, n_estimators=100;, score=0.708 total time=   0.2s
[CV 9/10; 7/20] START max_features=3, n_estimators=100..........................
[CV 9/10; 7/20] END max_features=3, n_estimators=100;, score=0.771 total time=   0.2s
[CV 10/10; 7/20] START max_features=3, n_estimators=100.........................
[CV 10/10; 7/20] END max_features=3, n_estimators=100;, score=0.771 total time=   0.2s
[CV 1/10; 8/20] START max_features=3, n_estimators=200..........................
[CV 1/10; 8/20] END max_features=3, n_estimators=200;, score=0.771 total time=   0.8s
[CV 2/10; 8/20] START max_features=3, n_estimators=200..........................
[CV 2/10; 8/20] END max_features=3, n_estimators=200;, score=0.792 total time=   0.6s
[CV 3/10; 8/20] START max_features=3, n_estimators=200..........................
[CV 3/10; 8/20] END max_features=3, n_estimators=200;, score=0.792 total time=   0.7s
[CV 4/10; 8/20] START max_features=3, n_estimators=200..........................
[CV 4/10; 8/20] END max_features=3, n_estimators=200;, score=0.750 total time=   0.7s
[CV 5/10; 8/20] START max_features=3, n_estimators=200..........................
[CV 5/10; 8/20] END max_features=3, n_estimators=200;, score=0.750 total time=   0.8s
[CV 6/10; 8/20] START max_features=3, n_estimators=200..........................
[CV 6/10; 8/20] END max_features=3, n_estimators=200;, score=0.750 total time=   0.8s
[CV 7/10; 8/20] START max_features=3, n_estimators=200..........................
[CV 7/10; 8/20] END max_features=3, n_estimators=200;, score=0.812 total time=   0.8s
[CV 8/10; 8/20] START max_features=3, n_estimators=200..........................
[CV 8/10; 8/20] END max_features=3, n_estimators=200;, score=0.708 total time=   0.4s
[CV 9/10; 8/20] START max_features=3, n_estimators=200..........................
[CV 9/10; 8/20] END max_features=3, n_estimators=200;, score=0.729 total time=   0.7s
[CV 10/10; 8/20] START max_features=3, n_estimators=200.........................
[CV 10/10; 8/20] END max_features=3, n_estimators=200;, score=0.750 total time=   0.7s
[CV 1/10; 9/20] START max_features=4, n_estimators=80...........................
[CV 1/10; 9/20] END max_features=4, n_estimators=80;, score=0.708 total time=   0.8s
[CV 2/10; 9/20] START max_features=4, n_estimators=80...........................
[CV 2/10; 9/20] END max_features=4, n_estimators=80;, score=0.729 total time=   1.0s
[CV 3/10; 9/20] START max_features=4, n_estimators=80...........................
[CV 3/10; 9/20] END max_features=4, n_estimators=80;, score=0.771 total time=   0.7s
[CV 4/10; 9/20] START max_features=4, n_estimators=80...........................
[CV 4/10; 9/20] END max_features=4, n_estimators=80;, score=0.750 total time=   0.7s
[CV 5/10; 9/20] START max_features=4, n_estimators=80...........................
[CV 5/10; 9/20] END max_features=4, n_estimators=80;, score=0.708 total time=   0.4s
[CV 6/10; 9/20] START max_features=4, n_estimators=80...........................
[CV 6/10; 9/20] END max_features=4, n_estimators=80;, score=0.708 total time=   0.3s
[CV 7/10; 9/20] START max_features=4, n_estimators=80...........................
[CV 7/10; 9/20] END max_features=4, n_estimators=80;, score=0.812 total time=   0.2s
[CV 8/10; 9/20] START max_features=4, n_estimators=80...........................
[CV 8/10; 9/20] END max_features=4, n_estimators=80;, score=0.729 total time=   0.2s
[CV 9/10; 9/20] START max_features=4, n_estimators=80...........................
[CV 9/10; 9/20] END max_features=4, n_estimators=80;, score=0.708 total time=   0.2s
[CV 10/10; 9/20] START max_features=4, n_estimators=80..........................
[CV 10/10; 9/20] END max_features=4, n_estimators=80;, score=0.771 total time=   0.2s
[CV 1/10; 10/20] START max_features=4, n_estimators=90..........................
[CV 1/10; 10/20] END max_features=4, n_estimators=90;, score=0.771 total time=   0.5s
[CV 2/10; 10/20] START max_features=4, n_estimators=90..........................
[CV 2/10; 10/20] END max_features=4, n_estimators=90;, score=0.771 total time=   0.5s
[CV 3/10; 10/20] START max_features=4, n_estimators=90..........................
[CV 3/10; 10/20] END max_features=4, n_estimators=90;, score=0.812 total time=   0.6s
[CV 4/10; 10/20] START max_features=4, n_estimators=90..........................
[CV 4/10; 10/20] END max_features=4, n_estimators=90;, score=0.750 total time=   0.5s
[CV 5/10; 10/20] START max_features=4, n_estimators=90..........................
[CV 5/10; 10/20] END max_features=4, n_estimators=90;, score=0.708 total time=   0.9s
[CV 6/10; 10/20] START max_features=4, n_estimators=90..........................
[CV 6/10; 10/20] END max_features=4, n_estimators=90;, score=0.729 total time=   0.7s
[CV 7/10; 10/20] START max_features=4, n_estimators=90..........................
[CV 7/10; 10/20] END max_features=4, n_estimators=90;, score=0.771 total time=   1.0s
[CV 8/10; 10/20] START max_features=4, n_estimators=90..........................
[CV 8/10; 10/20] END max_features=4, n_estimators=90;, score=0.729 total time=   0.6s
[CV 9/10; 10/20] START max_features=4, n_estimators=90..........................
[CV 9/10; 10/20] END max_features=4, n_estimators=90;, score=0.750 total time=   0.6s
[CV 10/10; 10/20] START max_features=4, n_estimators=90.........................
[CV 10/10; 10/20] END max_features=4, n_estimators=90;, score=0.771 total time=   0.6s
[CV 1/10; 11/20] START max_features=4, n_estimators=100.........................
[CV 1/10; 11/20] END max_features=4, n_estimators=100;, score=0.771 total time=   0.4s
[CV 2/10; 11/20] START max_features=4, n_estimators=100.........................
[CV 2/10; 11/20] END max_features=4, n_estimators=100;, score=0.792 total time=   0.6s
[CV 3/10; 11/20] START max_features=4, n_estimators=100.........................
[CV 3/10; 11/20] END max_features=4, n_estimators=100;, score=0.771 total time=   0.4s
[CV 4/10; 11/20] START max_features=4, n_estimators=100.........................
[CV 4/10; 11/20] END max_features=4, n_estimators=100;, score=0.729 total time=   0.5s
[CV 5/10; 11/20] START max_features=4, n_estimators=100.........................
[CV 5/10; 11/20] END max_features=4, n_estimators=100;, score=0.708 total time=   0.7s
[CV 6/10; 11/20] START max_features=4, n_estimators=100.........................
[CV 6/10; 11/20] END max_features=4, n_estimators=100;, score=0.729 total time=   0.5s
[CV 7/10; 11/20] START max_features=4, n_estimators=100.........................
[CV 7/10; 11/20] END max_features=4, n_estimators=100;, score=0.771 total time=   1.2s
[CV 8/10; 11/20] START max_features=4, n_estimators=100.........................
[CV 8/10; 11/20] END max_features=4, n_estimators=100;, score=0.729 total time=   1.0s
[CV 9/10; 11/20] START max_features=4, n_estimators=100.........................
[CV 9/10; 11/20] END max_features=4, n_estimators=100;, score=0.729 total time=   0.8s
[CV 10/10; 11/20] START max_features=4, n_estimators=100........................
[CV 10/10; 11/20] END max_features=4, n_estimators=100;, score=0.750 total time=   0.2s
[CV 1/10; 12/20] START max_features=4, n_estimators=200.........................
[CV 1/10; 12/20] END max_features=4, n_estimators=200;, score=0.771 total time=   0.6s
[CV 2/10; 12/20] START max_features=4, n_estimators=200.........................
[CV 2/10; 12/20] END max_features=4, n_estimators=200;, score=0.750 total time=   0.8s
[CV 3/10; 12/20] START max_features=4, n_estimators=200.........................
[CV 3/10; 12/20] END max_features=4, n_estimators=200;, score=0.771 total time=   0.6s
[CV 4/10; 12/20] START max_features=4, n_estimators=200.........................
[CV 4/10; 12/20] END max_features=4, n_estimators=200;, score=0.750 total time=   1.0s
[CV 5/10; 12/20] START max_features=4, n_estimators=200.........................
[CV 5/10; 12/20] END max_features=4, n_estimators=200;, score=0.729 total time=   1.3s
[CV 6/10; 12/20] START max_features=4, n_estimators=200.........................
[CV 6/10; 12/20] END max_features=4, n_estimators=200;, score=0.729 total time=   0.6s
[CV 7/10; 12/20] START max_features=4, n_estimators=200.........................
[CV 7/10; 12/20] END max_features=4, n_estimators=200;, score=0.812 total time=   0.7s
[CV 8/10; 12/20] START max_features=4, n_estimators=200.........................
[CV 8/10; 12/20] END max_features=4, n_estimators=200;, score=0.729 total time=   0.7s
[CV 9/10; 12/20] START max_features=4, n_estimators=200.........................
[CV 9/10; 12/20] END max_features=4, n_estimators=200;, score=0.729 total time=   0.5s
[CV 10/10; 12/20] START max_features=4, n_estimators=200........................

GridSearchCV(cv=10, estimator=RandomForestClassifier(),
             param_grid=[{'max_features': [2, 3, 4, 5, 6],
                          'n_estimators': [80, 90, 100, 200]}],
             verbose=100)

In [ ]:
gsv1.best_params_, gsv1.best_score_

({'max_features': 3, 'n_estimators': 80}, 0.7645833333333333)

In [ ]:
#let us build RandomForest model with these parameters

In [ ]:
model_rf=RandomForestClassifier(n_estimators=80, max_features=3)
model_rf.fit(X_train, Y_train)

RandomForestClassifier(max_features=3, n_estimators=80)

In [ ]:
kfold=KFold(n_splits=10, random_state=7, shuffle=True)

In [ ]:
results=cross_val_score(model_rf, X, Y, cv=kfold)
print(results.mean())

0.735

In [ ]:
tr_pred=model_rf.predict(X_train)

In [ ]:
confusion_matrix(Y_train, tr_pred)
#only 1 miss classification

array([[ 97,   1],
       [  0, 382]])

In [ ]:
print(classification_report(Y_train, tr_pred))
#accuracy is very high

              precision    recall  f1-score   support

         0.0       1.00      0.99      0.99        98
         1.0       1.00      1.00      1.00       382

    accuracy                           1.00       480
   macro avg       1.00      0.99      1.00       480
weighted avg       1.00      1.00      1.00       480

In [ ]:
accuracy_score(Y_train, tr_pred)   ###we have 99.79% accuracy for our training data

0.9979166666666667

In [ ]:
te_pred=model_rf.predict(X_test)
confusion_matrix(Y_test, te_pred)
#we have 29 miss classification

array([[ 1, 25],
       [ 4, 90]])

In [ ]:
print(classification_report(Y_test, te_pred))

              precision    recall  f1-score   support

         0.0       0.20      0.04      0.06        26
         1.0       0.78      0.96      0.86        94

    accuracy                           0.76       120
   macro avg       0.49      0.50      0.46       120
weighted avg       0.66      0.76      0.69       120

In [ ]:
accuracy_score(Y_test, te_pred)

0.7583333333333333

In [ ]:
#accuracy for testing data is 75%