In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.model_selection import cross_val_score

In [3]:
from google.colab import files
uploaded=files.upload()

Saving SalaryData_Train(1).csv to SalaryData_Train(1).csv

In [4]:
train=pd.read_csv("SalaryData_Train(1).csv")

In [5]:
from google.colab import files
uploaded=files.upload()

Saving SalaryData_Test(1).csv to SalaryData_Test(1).csv

In [6]:
test=pd.read_csv("SalaryData_Test(1).csv")

In [7]:
test.head(2)

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K

In [8]:
train.head(2)

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K

In [9]:
train.shape

(30161, 14)

In [10]:
test.shape

(15060, 14)

In [11]:
data=pd.concat([train, test])

In [12]:


data.shape

(45221, 14)

In [13]:
array1=train.values
array2=test.values

In [14]:




data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45221 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            45221 non-null  int64
 1   workclass      45221 non-null  object
 2   education      45221 non-null  object
 3   educationno    45221 non-null  int64
 4   maritalstatus  45221 non-null  object
 5   occupation     45221 non-null  object
 6   relationship   45221 non-null  object
 7   race           45221 non-null  object
 8   sex            45221 non-null  object
 9   capitalgain    45221 non-null  int64
 10  capitalloss    45221 non-null  int64
 11  hoursperweek   45221 non-null  int64
 12  native         45221 non-null  object
 13  Salary         45221 non-null  object
dtypes: int64(5), object(9)
memory usage: 5.2+ MB

In [15]:
data.describe()

                age   educationno   capitalgain   capitalloss  hoursperweek
count  45221.000000  45221.000000  45221.000000  45221.000000  45221.000000
mean      38.548086     10.118463   1101.454700     88.548617     40.938038
std       13.217981      2.552909   7506.511295    404.838249     12.007640
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       47.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   4356.000000     99.000000

In [16]:



#Let us use label encoder for encoding our data
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
train[['workclass','education','maritalstatus','occupation','relationship','race','sex'	,'native','Salary']]=train[['workclass','education','maritalstatus','occupation','relationship','race','sex'	,'native','Salary']].apply(LabelEncoder().fit_transform)
train

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,5,9,13,4,0,1,4,1,2174,0,40,37,0
1,50,4,9,13,2,3,0,4,1,0,0,13,37,0
2,38,2,11,9,0,5,1,4,1,0,0,40,37,0
3,53,2,1,7,2,5,0,2,1,0,0,40,37,0
4,28,2,9,13,2,9,5,2,0,0,0,40,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30156,27,2,7,12,2,12,5,4,0,0,0,38,37,0
30157,40,2,11,9,2,6,0,4,1,0,0,40,37,1
30158,58,2,11,9,6,0,4,4,0,0,0,40,37,0
30159,22,2,11,9,4,0,3,4,1,0,0,20,37,0
30160,52,3,11,9,2,3,5,4,0,15024,0,40,37,1

In [17]:


test[['workclass','education','maritalstatus','occupation','relationship','race','sex'	,'native','Salary']]=test[['workclass','education','maritalstatus','occupation','relationship','race','sex'	,'native','Salary']].apply(LabelEncoder().fit_transform)
test

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,2,1,7,4,6,3,2,1,0,0,40,37,0
1,38,2,11,9,2,4,0,4,1,0,0,50,37,0
2,28,1,7,12,2,10,0,4,1,0,0,40,37,1
3,44,2,15,10,2,6,0,2,1,7688,0,40,37,1
4,34,2,0,6,4,7,1,4,1,0,0,30,37,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15055,33,2,9,13,4,9,3,4,1,0,0,40,37,0
15056,39,2,9,13,0,9,1,4,0,0,0,36,37,0
15057,38,2,9,13,2,9,0,4,1,0,0,50,37,0
15058,44,2,9,13,0,0,3,1,1,5455,0,40,37,0
15059,35,3,9,13,2,3,0,4,1,0,0,60,37,1

In [ ]:
#x_train=train.iloc[:,0:13]
#y_train=train.iloc[:,13]

In [ ]:
#x_test=test.iloc[:,0:13]
#y_test=test.iloc[:,13]

In [18]:
X=train.iloc[:,0:13]
Y=train.iloc[:,13]

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test , Y_train, Y_test= train_test_split(X,Y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape,  Y_train.shape, Y_test.shape

((21112, 13), (9049, 13), (21112,), (9049,))

In [20]:
#we have encoded our data

Randomized search cv

In [ ]:
#Here we have 3 hyperparameters hence we will go with randmized searchCV or gridsearchCV, K-fold works only with 1 hyperparameter

In [ ]:
clf=SVC()                                                                                      #classifier-clf, SVC is our model

param_grid = [{'kernel':['rbf', 'linear'],'gamma':[0.1,0.5],'C':[10,0.1] }]
gsv=RandomizedSearchCV(clf,param_grid, cv=5, verbose=300)                                    #we re storing randomized search in gsv #verbose is no.of lines we want to see in our output

In [ ]:
gsv.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:305: UserWarning: The total space of parameters 8 is smaller than n_iter=10. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV 1/5; 1/8] START C=10, gamma=0.1, kernel=rbf.................................
[CV 1/5; 1/8] END ..C=10, gamma=0.1, kernel=rbf;, score=0.782 total time=  57.1s
[CV 2/5; 1/8] START C=10, gamma=0.1, kernel=rbf.................................
[CV 2/5; 1/8] END ..C=10, gamma=0.1, kernel=rbf;, score=0.785 total time=  57.4s
[CV 3/5; 1/8] START C=10, gamma=0.1, kernel=rbf.................................
[CV 3/5; 1/8] END ..C=10, gamma=0.1, kernel=rbf;, score=0.783 total time=  56.3s
[CV 4/5; 1/8] START C=10, gamma=0.1, kernel=rbf.................................
[CV 4/5; 1/8] END ..C=10, gamma=0.1, kernel=rbf;, score=0.770 total time=  59.4s
[CV 5/5; 1/8] START C=10, gamma=0.1, kernel=rbf.................................
[CV 5/5; 1/8] END ..C=10, gamma=0.1, kernel=rbf;, score=0.779 total time=  55.9s
[CV 1/5; 2/8] START C=10, gamma=0.1, kernel=linear..............................

In [ ]:
gsv.best_params_, gsv.best_score_   #it gives the best hyperparameters and the accuracy

In [21]:
#Let us build our model
clf=SVC(kernel='rbf', gamma=0.1, C=10)
clf.fit(X_train, Y_train)

SVC(C=10, gamma=0.1)

In [22]:
y_pred=clf.predict(X_test)

In [23]:
#let us check the accuracy of our model
from sklearn.metrics import accuracy_score, confusion_matrix
acc=accuracy_score(Y_test, y_pred)*100
print("Accuracy:  ", acc)
confusion_matrix(Y_test, y_pred)

Accuracy:   78.57221792463255

array([[6195,  585],
       [1354,  915]])

In [ ]:
#we got an acyracy of 78.5 % for the testing data.